Pap 138 install prettier linter and jest on intracom webapp
project-ascend-io/intracom-webapp pull request #5
Opened 2024-08-16 14:58 UTC by Amenu-sh

## Problem
Code Quality and standardize

## Solution
Test the configuration and resolve any issues.

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Implemented Prettier, linter, jest, Commitlint, and husky.

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-08-28 01:38 UTC, oestrada1001 requested changes

2024-08-28 01:38 UTC, oestrada1001 commented on .husky/commit-msg
> +. "$(dirname "$0")/_/husky.sh"
**Actionable**
Line 2 and 3 are not required with the latest version of husky

2024-08-28 01:38 UTC, oestrada1001 commented on public/zoom 2.png
**Actionable**
Please remove these images if they aren't being used.

2024-08-28 01:38 UTC, oestrada1001 commented on public/service 2.png
**Actionable**
Please remove this image if it isn't being used.

2024-08-28 01:38 UTC, oestrada1001 commented on public/preporganization 2.png
**Actionable**
Please remove this image if it isn't being used.

2024-08-28 01:38 UTC, oestrada1001 commented on public/jira 2.png
**Actionable**
Please remove this image if it isn't being used.

2024-08-28 01:38 UTC, oestrada1001 commented on public/gitlab 2.png
**Actionable**
Please remove this image if it isn't being used.

2024-08-28 01:38 UTC, oestrada1001 commented on public/github 2.png
**Actionable**
Please remove this image if it isn't being used.

2024-08-28 01:38 UTC, oestrada1001 commented on src/app/Successful/page.tsx
**Actionable**
Let's make sure the directory name is 'successful' with a lowercase 's' when we merge to main.

2024-08-28 01:38 UTC, oestrada1001 commented on src/app/layout.tsx
> +  title: 'Create Next App',
**Actionable**
Please revert title and and description.
```
Title: 'Intracom'
Description: ''
```

2024-08-28 03:05 UTC, Amenu-sh commented on public/zoom 2.png
images are used inside the Preparing-workspace component.

2024-08-28 03:12 UTC, Amenu-sh commented on public/preporganization 2.png
doubled images are being removed.

2024-09-04 21:42 UTC, oestrada1001 approved these changes
Looks great! Great job @Amenu-sh!

2024-09-07 01:37 UTC, merged